# Generated by Django 5.2.1 on 2025-05-19 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('local', 'Mahalliy vazifa'), ('global', 'Xalqaro vazifa')], default='local', max_length=10, verbose_name='Vazifa turi')),
                ('maqola', models.FileField(blank=True, null=True, upload_to='maqolalar/')),
                ('tezis', models.FileField(blank=True, null=True, upload_to='tezislar/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment_comment', models.TextField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('kafedra', models.ForeignKey(blank=True, limit_choices_to={'role': 'kafedra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Baholagan kafedra')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ustoz'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ustoz')),
            ],
        ),
    ]
