# Generated by Django 5.2.1 on 2025-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='jurnal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
