# Generated by Django 5.2.1 on 2025-05-25 11:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tasksubmission_task_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('kafedraTaskType', models.CharField(choices=[('books', 'Kafedra kitobi'), ('instruction', "O'quv qo'llanma"), ('scientific_work', 'Ilmiy ish')], default='books', max_length=100)),
                ('kafedraUpload', models.FileField(blank=True, null=True, upload_to='kafedra_files/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('jurnal', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kafedra', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(default='', related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
