# Generated by Django 5.2.1 on 2025-05-25 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_kafedramaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('local', 'Mahalliy vazifa'), ('global', 'Xalqaro vazifa')], default='local', verbose_name='Vazifa turi')),
                ('task_upload', models.CharField(choices=[('olimpics', 'olimpiada'), ('', 'Musoboqa'), ('student_employment', 'Talaba bandligi')], default='olimpics')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='student_award/')),
                ('date', models.DateField(blank=True, null=True)),
                ('student_fname', models.TextField(blank=True, null=True)),
                ('student_course', models.TextField(blank=True, null=True)),
                ('student_kafedra', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kafedramaterial',
            name='teachers',
            field=models.ManyToManyField(default='', limit_choices_to={'role': 'ustoz'}, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
