# Generated by Django 5.2.1 on 2025-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_studentawards_alter_kafedramaterial_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentawards',
            name='task_upload',
            field=models.CharField(choices=[('olimpics', 'olimpiada'), ('competition', 'Musoboqa'), ('student_employment', 'Talaba bandligi')], default='olimpics'),
        ),
    ]
