# Generated by Django 5.2.1 on 2025-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_studentawards_task_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentawards',
            name='student_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentawards',
            name='student_fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentawards',
            name='student_kafedra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentawards',
            name='task_upload',
            field=models.CharField(choices=[('olimpics', 'Olimpiada'), ('competition', 'Musoboqa'), ('student_employment', 'Talaba bandligi')], default='olimpics', verbose_name='Mukofot turi'),
        ),
    ]
