# Generated by Django 5.2.1 on 2025-05-19 11:22

import django.utils.timezone
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('full_name', models.CharField(blank=True, default='', help_text='Iltimos, to‘liq ismingizni kiriting.', max_length=255, validators=[user.validators.validate_f_name], verbose_name='To‘liq ism')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('p_number', models.CharField(blank=True, default='', help_text='Iltimos, raqamni to‘g‘ri kiriting. Masalan: +998123456789', max_length=13, validators=[user.validators.PhoneValidator()], verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('dekan', 'Dekan'), ('kafedra', 'Kafedra'), ('ustoz', 'Ustoz')], default='ustoz', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
