# Generated by Django 5.2.1 on 2025-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tajriba'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('kafedra_ustoz', 'Kafedra ustoz'), ('phd_ustoz', 'PhD ustoz'), ('dsc_ustoz', 'DSc ustoz')], default='kafedra_ustoz', max_length=20, null=True, verbose_name='Ustoz turi'),
        ),
    ]
