# Generated by Django 5.2.1 on 2025-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_experience_user_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dekan', 'Dekan'), ('kafedra', 'Kafedra'), ('ustoz', 'Ustoz'), ('award_manager', 'Achievement Manager')], default='ustoz', max_length=20),
        ),
    ]
